export const LOGGED_IN_USER = "LOGGED_IN_USER";
export const LOGOUT = "LOGOUT";
export const SERVICE_DATA = "SERVICE_DATA";
export const SEARCH_QUERY = "SEARCH_QUERY";
export const SERVICE_VIEW = "SERVICE_VIEW";
export const FILTER_SERVICES_BY_LOCATION = "FILTER_SERVICES_BY_LOCATION";
